    /*
 * This source file was generated by the Gradle 'init' task
 */
package applicazione;

import javax.swing.JFrame;

import applicazione.controller.Controller;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        new Controller(frame);
    }
}
